### ISSUE TITLE
Error when running budget-report

### ISSUE THREAD

**Issue by ghudspeth** [sulemankm/budget_report#2]
Tried to run my first budget report and receive the following error:

(venv) glenn@DESKTOP-4CFGTH6:~/finances$ budget-report -s 2022-01-01 journal.beancount
Traceback (most recent call last):
  File "/home/glenn/finances/venv/bin/budget-report", line 8, in <module>
    sys.exit(script_main())
  File "/home/glenn/finances/venv/lib/python3.8/site-packages/budgetreport/main.py", line 27, in script_main
    br = report.generateBudgetReport(entries, options_map, args)
  File "/home/glenn/finances/venv/lib/python3.8/site-packages/budgetreport/report.py", line 139, in generateBudgetReport
    budgetted_accounts = collectBudgetAccounts(entries, options_map, args, br)
  File "/home/glenn/finances/venv/lib/python3.8/site-packages/budgetreport/report.py", line 100, in collectBudgetAccounts
    entry.values[1].value.number))
AttributeError: 'str' object has no attribute 'number'
(venv) glenn@DESKTOP-4CFGTH6:~/finances$

**Comment by sulemankm** [comment]
Hi, Thanks for the input.  I have already addressed this issue in the upcoming release 0.3.

You should have version 0.2 installed, as I am testing version 0.3 right now and it is not yet published to PyPI yet.  You can check your version with '-v' switch.  As the README.md mentions, you should not include the budget period eg "month" etc while specifying budget in your input file.  For example as below:

2021-12-06 custom "budget" Expenses:Car:Fuel         5000 RS ; Note! no budget period here!

**Comment by ghudspeth** [comment]
Works perfectly now. Thank you! Would be cool if we could specify the number of decimal places in the report, as I am accustomed to seeing two for USD cents. Thank you for your work.
